Issue 1 create an entry
Alex-Davis0/code-journal pull request #5
Opened 2021-12-21 22:54 UTC by Alex-Davis0

2021-12-21 22:54 UTC, Alex-Davis0 commented
![Code-journal 1](https://user-images.githubusercontent.com/93169087/147008106-c697fd6f-292f-4a36-8e6a-262875da9367.gif)
![Code-journal 2](https://user-images.githubusercontent.com/93169087/147008113-7fc59e4e-4b89-4f13-8056-036c4d74c092.gif)

2021-12-21 22:58 UTC, Zhiwutian requested changes
looking good, just some local storage updates!

2021-12-21 22:58 UTC, Zhiwutian commented on js/main.js
> +  localStorage.setItem('data-profile', JSON.stringify(data));
make sure that all local storage functionality is completed in the data.ja file. Also, that functionality should match the functionality in the `javascript local storage` exercise. Local storage should only be used to load data at start, and store it at refresh.

2021-12-22 00:06 UTC, Zhiwutian approved these changes
👍🏼

2021-12-22 00:08 UTC, merged